'use strict';

require('util.global');
require('_constants');
require('_config');
require('roomobject.define');
require('roomobject.extend');
require('creep.define');
require('creep.extend');
require('room.define');
require('room.extend');
// require('roomposition.define');
// require('roomposition.extend');
require('source.define');
// require('source.extend');
require('structure.define');
require('structure.extend');
require('spawn.extend');
require('controller.extend');
require('controller.define');
// require('flag.define');
// require('flag.extend');
// require('constructionsite.define');
// require('constructionsite.extend');
require('role.harvester');
require('role.hauler');
require('role.upgrader');
require('role.builder');
require('role.defender');
